### ISSUE TITLE
Make it possible to plot 2d and 3d ellipsoids from the same array

### ISSUE THREAD

**Issue by pgagarinov** [SystemAnalysisDpt-CMC-MSU/ellipsoids#23]
Right now a call like this

ellVec=[ellipsoid(eye(2)),ellipsoid(eye(3))];

is not supported. One needs to make it possible. Most of the points from issue #22 are useful here as well.

1) The implemented functionality should be covered with tests implemented in the following test pack.
+elltool+core+test+mlunit\GenEllipsoidPlotTestCase. In the test one needs to consider different combinations of input parameters and array sizes. Negative tests are also required. See Wiki for an example of a negative test (mlunitext.test_case.runAndCheckError).

2) No copy-pasting, compliance with the coding style (see Wiki) and presence of code comments. 
No commented out code, no blank lines, no long lines.

**Comment by irublev** [comment]
All is done within issue #52
