### ISSUE TITLE
Fix doesIntersectionContain for mode="i"

### ISSUE THREAD

**Issue by pgagarinov** [SystemAnalysisDpt-CMC-MSU/ellipsoids#27]
Deadline is 25th of October
--------------------------------------------------------------------------------------
doesIntersectionContain method uses qcqp subfunction for the intersection case (mode = 'i')
qcqp function uses minimization of quadratic form

minimize(xVec'*invQMat*xVec + 2*(-invQMat*qVec)'*xVec + ...
    (qVec'*invQMat*qVec - 1))
	
which is incorrect and contradicts the function description in the help header.

All this means that there are no any tests right now neither in 
C:\Users\Administrator\Documents\_Ellipsoids\ellipsoids\products\+elltool\+core\+test\+mlunit\EllSecTCMultiDim.m
nor in any other test case that check this particular case of intersection. 

Please 
1) Write a few non-trivial tests that check that particular case and make sure that they fail. Or, if you find some existing tests from
EllSecTCMultiDim (or any other test case) that can be slightly tweaked/enhanced to capture this problem - do that instead of writing completely new tests.
2) Change minimize to maximize and make sure that all the tests pass (old and new).

**Comment by pgagarinov** [comment]
Good evening, 
I've found that when I replace minimize to maximize cvx throw error:
"Cannot maximize a(n) convex expression."

There are writen following
"CVX supports three different types of disciplined convex programs:
A minimization problem, consisting of a convex objective function and zero or more constraints.
A maximization problem, consisting of a concave objective function and zero or more constraints.
A feasibility problem, consisting of one or more constraints and no objective."
on the http://web.cvxr.com/cvx/doc/dcp.html "Top-level rules" section.

So, does I need to realize this functionality, either it is too hard for warm-up exercise?

Thanks,
Lubimov A. I. 
-----------------------------------------------------
Peter Gagarinov
To: Arthur 
See section 4.4 on page 152 in Boyd's "Convex Optimization"
https://drive.google.com/open?id=0B5OqL4IVOIC8RHpWYTRvYlRGeHc
that confirms that the problem is not convex so you are right that it is not trivial. I hoped that CVX solver can actually handle this problem by at least finding a local maximum but looks like it cannot do it. 

I suggest the following plan to be 100%:

1) you create a simple test that makes sure that the function as it is implemented right now (with minimum) doesn't work correctly i.e. it cannot correctly determine if an ellipsoid belongs to an intersection of other ellipsoids.

2) You change the implementation to use ellipsoid.doesContain function to veryfy that fstEll is contained within each of ellipsoids from secEllArr. Please note that doesContain uses S-procedure to check for an ellipsoid containment (see page 655 from the same book).

3) You make sure that the tests now pass.

**Comment by pgagarinov** [comment]
Please do rebase of your branch to master - I fixed a problem in "master" branch that prevented a correct execution of tests in your branch. 

Also, please note that the issue is considered to be fixed only when it is merged into master. Only I can close issues.

**Comment by pgagarinov** [comment]
4) Please fix the grammar mistake in "ET for now do not support"
5) Merge your changes into master following these steps:

    1) Switch to master
    2) Merge -> from -> origin/remotes/your branch (using local branch can dangerous because it can      contain unpushed changes) 
    3) Important !!! Set "no fast forward flag". Press OK
    4) DO NOT PUSH JUST YET. Right click and open log. It should look like "petlya".
    5) If eveything is ok - press push. 
    6) Wait for the test results for updated master. If everything ok - switch to the next task which will be assigned to your very shortly.

**Comment by pgagarinov** [comment]
You cannot merge to master if at least 1 test in your branch fails. This is what happened in this case.
After each change you need to find the test results for your branch in https://groups.google.com/forum/#!forum/ellipsoids-tests-notification google group and make sure that all tests pass. 

Obviously you didn't do that so I've reverted your changes to master.



Your test should be negative i.e. it should not fail (use runAndCheckError - see Wiki for more details). Here is the error I see. 

Error Message

Error: ET for now does not supportsolving non-convex QCQP problems.This functionality will be implemented in the future, Identifier: ELLIPSOID:DOESINTERSECTIONCONTAIN:notSupportedMode
Stacktrace

Traceback (most recent call first): 
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\elltoolboxcore\@ellipsoid\doesIntersectionContain.m at line 177
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\+elltool\+core\+test\+mlunit\EllipsoidSecTestCase.m at line 725
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\+elltool\+core\+test\+mlunit\EllipsoidSecTestCase.m at line 22
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\test_case.m at line 266
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\test_suite.m at line 470
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\+modgen\+pcalc\auxdfevalpcomp.m at line 286
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\+modgen\+pcalc\auxdfeval.m at line 124
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\+pcalc\auxdfeval.m at line 9
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\test_suite.m at line 438
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\test_suite.m at line 470
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\+modgen\+pcalc\auxdfevalpcomp.m at line 286
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\+modgen\+pcalc\auxdfeval.m at line 124
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\+pcalc\auxdfeval.m at line 9
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\test_suite.m at line 438
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\text_test_runner.m at line 86
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\+elltool\+core\+test\run_tests.m at line 23
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\+elltool\+test\run_tests.m at line 5
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\mlunitext\+mlunitext\RemoteTestRunner.m at line 45
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\lib\+modgen\+mlunit\run_tests_remotely.m at line 52
in C:\_JenkinsHome\workspace\EllTbx_Win64_2015b\master\products\+elltool\+test\run_tests_remotely.m at line 24

**Comment by AiLubimov** [comment]
Can I merge?
https://groups.google.com/forum/#!topic/ellipsoids-tests-notification/RohpaksSp9g

**Comment by pgagarinov** [comment]
Yes but please remove round brackets in 

if (doesIntersectionContain(ell, poly) == 1)

first, they are not necessary.

**Comment by pgagarinov** [comment]
Please have a look at my commit "02138484e421fae53003b6895a43cb708022b83c" in master. This commit fixes a problem with function-like calls that do not work in Matlab 2013b. Please do not use such calls unless it is absolutely necessary, i.e. call method like obj.methodName(arg1,arg2,...), not like methodName(obj,arg1,arg2,..). This might not work correctly even in Matlab2015b especially if methodName is defined not just for obj but also for arg1 for instance. Do you see?

**Comment by AiLubimov** [comment]
Yes, I see. I'll keep it on mind.
