### ISSUE TITLE
Allow for small imaginary parts in input matrices for a number of methods/functions in ET

### ISSUE THREAD

**Issue by pgagarinov** [SystemAnalysisDpt-CMC-MSU/ellipsoids#36]
Deadline is 3rd of November 2015
----------------------------------------------------------------------------------------------
1) Implement resMat=gras.la.trytreatasreal(inpMat,tolVal) function where tolVal is optional argument with a default value = eps 
(floating-point relative accuracy in Matlab, type "doc eps" for more details). The function should do the following:
a) check if inpMat is real - if positive - resMat = inpMat, else - calculate an imaginary part of inpMat: imagInpMat=imag(inpMat) and compare its norm(x,Inf) with tolVal.
if norm(imagInpMat,Inf)<tolVal then return resMat= real(inpMat); otherwise - throw an exception (use modgen.common.throwerror) that says something like
 "input matrix cannot be considered real as a 1.3233e-10 (norm of imaginary part) > (tolVal)1e-18"
 
This function should also work for vectors.

2) Write a few tests (both positive and negative) that check that this function works correctly.
 
3) In all the places below replace check that use "isreal" with calls to resMat=gras.la.trytreatasreal(inpMat) with a single input argument. 
The idea is to let all these functions(methods) accept matrices with very small imaginary parts just as if they were real matrices (imaginary part is thrown away).

(especially if function/method can be called with different number/combination of input arguments) of passing a matrix,vector
products\+gras\+la\orthtransl.m	21	if ~isreal(srcVec)
products\+gras\+la\orthtransl.m	25	if ~isreal(dstVec)
products\+gras\+la\orthtranslqr.m	20	if ~isreal(srcVec)
products\+gras\+la\orthtranslqr.m	24	if ~isreal(dstVec)
products\+gras\+la\regmat.m	20	'isscalar(x)&&isreal(x)&&isnumeric(x)&&(x>0)');
products\+gras\+la\regposdefmat.m	19	'isscalar(x)&&isreal(x)&&isnumeric(x)&&(x>0)');
\products\elltoolboxcore\@ellipsoid\ellipsoid.m	217	checkvar(regParamList{1},@(x) isa(x,'double')&&isreal(x),...
\products\elltoolboxcore\@ellipsoid\ellipsoid.m	235	isreal(x) && isreal(y),2,regParamList{1},regParamList{2},...
\products\elltoolboxcore\@ellipsoid\fromRepMat.m	65	checkvar(sizeVec,@(x) isa(x,'double')&&all(isreal(x(:)))&&...
\products\elltoolboxcore\@hyperplane\fromRepMat.m	58	checkvar(sizeVec,@(x) isa(x,'double')&&all(isreal(x(:)))&&...

4) For all these functions/functions from the list above write test that check every case of passing matrices with very small imaginary parts and make sure that
everything works as planned i.e. if matrix has an imaginary part that is less or equalthan eps (eps/2 or eps for instance) then these functions work as if the matrix was real.
Otherwise the exception is thrown (negative tests for such case should also be written). Please note that each test should be written in a corresponding test case located next to the function it tests.

**Comment by ilya2015** [comment]
Good morning. I have one question - how can i will test ellipsoid and hyperplane classes? During elltool.test.run_tests they are checked by demo examples..
P.S. Description of last commit is incorrect: i used isreal(trytreatasreal()).

**Comment by pgagarinov** [comment]
Good evening,

1)
> During elltool.test.run_tests they are checked by demo examples..
I'm not sure I agree with that.
If are are talking about elltool.demo.test.run_demo_tests then if you look inside C:\Users\Administrator\Documents\_Git\ellipsoids\products\+elltool\+demo\+test\run_tests.m you should see that line 14 is commented out. This is because demo functions take too long to run.

2) 
>how can i test @ellipsoid and @hyperplane classes?
Well, there is a plenty of tests called by elltool.core.test.run_tests script. elltool.test.run_tests calls this script so ellipsoid and hyperplain classes are not covered only by demo stuff.

**Comment by pgagarinov** [comment]
Regarding your last commit - I think you have missed the whole idea because  if you hadn't the following piece of code would have had any sense to you:

+if ~isreal(trytreatasreal(srcVec))
     throwerror('wrongInput:srcComplex',...
         'source vector is expected to be real');
 end

Let me explain. The idea is that trytreatasreal is expected to throw an exception by itself if an imaginary part is too large. So all "if ~isreal" outside this function should be gone.

**Comment by ilya2015** [comment]
Do i understand correctly:
1) i will add to current trytreatasreal function checking the value of real part - if it is too large then throw exception.
2) add test for item (1) to \products\+gras\+la\+test\+mlunit\BasicTestCase.m
3) add test for each function from list

**Comment by pgagarinov** [comment]
1) Yes, but trytreatasreal  not just does the checking, it also returns real part if complex part is not too large.

2) Yes, both positive and negative tests. Positive tests check that the returned result matches the expected result. Negative test checks that thrown exception matches the expected exception (see Wiki for MLUNITEXT).

3) Yes, a few tests both negative and positive for each.

**Comment by ilya2015** [comment]
You said: "trytreatasreal not just does the checking, it also returns real part if complex part is not too large." But which value to constrain complex part on top?

**Comment by pgagarinov** [comment]
Here is from my description:

1) Implement resMat=gras.la.trytreatasreal(inpMat,tolVal) function where tolVal is optional argument with a default value = eps 
(floating-point relative accuracy in Matlab, type "doc eps" for more details). The function should do the following:

so tolVal is upper constraint for norm of complex part. If it is not specified, use Matlab constant `eps`. Does this answer your question?

**Comment by ilya2015** [comment]
I mean do we need to check for too much real or imaginary part? Becouse i think that if norm() is very big then we can throw exeption too.

**Comment by pgagarinov** [comment]
We throw an exception only if norm (imagMat,Inf) > tolVal

**Comment by pgagarinov** [comment]
About last commit
1) There are no negative tests still, not tests for all functions that use "trytreaasreal" (see the task description)
2) Please make the error message produced by the function "trytreatasreal" more specific by by including values of both the norm of imaginary part and tolVal.

**Comment by ilya2015** [comment]
Now i have one problem. If i replaced part of function (for example orthtransl.m):
"if ~isreal(srcVec)
    throwerror('wrongInput:srcComplex',...
        'source vector is expected to be real');
end"
to
"srcVec = gras.la.trytreatasreal(srcVec);"
then a failure occurs:
"no match found for pattern identifier(wrongInput:srcComplex)message() exception details".
But i tested trytreatasreal function with my examples, and it worked correctly.

**Comment by pgagarinov** [comment]
Can you please provide more information - where you did this replacement and what does test fail?

**Comment by ilya2015** [comment]
For example i replaced 21-23 strings in file ...\products\+gras\+la\orthtransl.m to "srcVec = gras.la.trytreatasreal(srcVec);".
I added output to trytreatasreal function, because i thought that this is method for catch exception in BasicTest function. Maybe is another method for catch exception?

**Comment by pgagarinov** [comment]
Ok, you obviously did something wrong. Let us start from the beginning. Your function throws an exception in a "bad" situation. Your test should check that when data is "bad" a) exception is thrown b) identifier of the exception is what the test expects. 

One way to do that would be writing try catch statement in the test and them checking a content of caught exception directly. However, there is a simpler way - runAndCheckError method of the test case that does all the checking by itself.

Thus you should not catch exceptions directly - you should use "runAndCheckError" method of mlunitext.test_case class - see "writing negative tests" in 

https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/wiki/MLUNITEXT-unit-testing-framework-description.

Now, if you have a problem with a negative test that should pass but doesn't pass for some reason - set a breakpoint at line 392 in C:\Users\Administrator\Documents\_Git\ellipsoids\lib\mlunitext\+mlunitext\test_case.m
and see what "meObj.identifier" contains.

**Comment by ilya2015** [comment]
I find both new problems:
1) File \products\+gras\+la\regmat.m had not any test.  I should create it? 
Also how i understand, this function is used only in \products\+gras\+mat\MatrixReg.m.
2) I can not tested method \products\elltoolboxcore\@hyperplane\fromRepMat.m with help elltool.core.test.run_tests (if i comment 58-61 strings in fromRepMat function then result does not change). Maybe are another tests for it?

**Comment by pgagarinov** [comment]
1) Yes, please
2) Please add the test for fromRepMat into HyperplaneTestCase.
3) Are there any tests for ellipsoid.fromRepMat? if not - please add the test to this method as well to EllipsoidTestCase
4) Just let me know when you think you are finished so that I can start looking. Thanks.

**Comment by ilya2015** [comment]
1) - 2) has been added
3) There were this tests in previous commit
4) I hope that i finished.

**Comment by pgagarinov** [comment]
5) please do not use square brackets in if conditions, if (~isa(sizeVec,'double')) - > if ~isa(sizeVec,'double')

6) in ellipsoid constructor here 

                    regParamList{1} = gras.la.trytreatasreal (regParamList{1});
                    checkvar(regParamList{1},@(x) isa(x,'double'),...
                        'errorTag', 'errorMessage',...
                        'shapeMat matrix must be real.');
                    shMatArray = regParamList{1};


let us just extract shMatArray first and then use it in both trytreatasreal and checkvar instead of using regParamList{1} everywhere

7) in trytreatasreal please write a correctly formed help header - see Wiki and modgen.common.parseparamext as an example.
Also please check that tolVal is a positive numeric scalar (isnumeric, isscalar, >0). Please do this directly in the code 
instead of using modgen.common.checkvar because trytreatasreal should be very fast.

8) Are you sure that mlint warning suppression is needed in SuiteOrthTransl in

            dstVec=[1 0]; %#ok<*NASGU>
?

9)  
mlunitext.assert expects a scalar while == in SuiteOrthTransl :

            mlunitext.assert(oimagMat == orealMat, ...
                'Incorrect work orthtransl function');
            %

returns a logical matrix. Please use isequal instead of ==

You do the same in other tests as well - please fix all the places.

10) I didn't find any negative tests for 

products\+gras\+la\orthtransl.m
products\+gras\+la\orthtranslqr.m
products\+gras\+la\regposdefmat.m

**Comment by ilya2015** [comment]
I fixed 5-9 problems.
But negative tests were in previous version:
1) For products+gras+la\orthtransl.m and products+gras+la\orthtranslqr.m there are some tests in file SuiteOrthTransl (19-29 strings).
2) products+gras+la\regposdefmat.m - in BasicTestCase (362 - 379 strings).

**Comment by pgagarinov** [comment]
5) there are still a lot of square brackets in if conditions

hyperplane.fromMat - 
ellipsoid.fromMat - 

if (~isa(sizeVec,'double'))

if (~isa(sizeVec,'double'))


trytreatasreal

if (isreal(inpMat))

10) please do not use spaces in expressions like this 

mlunitext.assert(isequal (oimagMat, orealMat), ...

For some reason you put a lot of spaces after isequal and before the second argument. Please remove them.

11) 
please do not use ' for transposition as ' corresponds to conjunction. For transposition use .' or transpose.

**Comment by ilya2015** [comment]
5) and 10) has been fixed, but i did not use operator '.

**Comment by pgagarinov** [comment]
Please do rebase and then merge into master as previous branch, be very careful.

**Comment by ilya2015** [comment]
Sorry, but i forgot delete old branch #25 and pushed it too. Can you delete it, please?

**Comment by pgagarinov** [comment]
You did everything wrong. 1) You didn't change the master. 2) You graph for 36 now is not flat. 
When you do pull you should always use "launch rebase after fetch". You should not merge remotes/origin/issue36 with your local issue36 and that is what happened.

Now you need to open log for your local branch, select commit "11dcfdc49c8377318810105fd566ede0cf74e099" (the one preceeding the merge commit), run "reset issue36 to this commit" and select "hard". After that do everything all over again following the instructions from issue 25.

Btw - the old branch for 25 was deleted on a remote server, all that remained is your local copy that you need to delete by yourself.

**Comment by ilya2015** [comment]
I reverted changes of my local branch, but Tortoisegit does not see remotes/origin/Issue_36_IlyaSh. Can i push it to origin and after this do instructions from issue 25?

**Comment by pgagarinov** [comment]
Yes, you can.
6 нояб. 2015 г. 13:46 пользователь "Shirokikh Ilia" <
notifications@github.com> написал:

**Comment by ilya2015** [comment]
You sad that i should revert my local branch, but when i merge i must use remotes/origin/Issue_36_IlyaSh (how i did in #25)? Maybe i can revert my origin's branch ?

**Comment by pgagarinov** [comment]
There are multiple ways to do the same thing. You can revert local, push to remote and merge from remote. Or, you can revert local and merge from local directly. The potential problem with the second option is that you can merge to master something that I didn't see. But in this particular case this is not a problem as long as you do not make any more commits to your local branch. 

Does it make sense? If you do not understand something - just let me know but please do not do semething blindly just because I say so. You neef to understand what you do and why. Thanks.

**Comment by pgagarinov** [comment]
In git you cannot work directly on remote branches,  the only way you can change remote branch ( i.e remote/origin/yourbranch) is via push from local branch (the one without rwmote/origin prefix)
