### ISSUE TITLE
Implement a few methods of "ellipsoid" class in "GenEllipsoid" class

### ISSUE THREAD

**Issue by pgagarinov** [SystemAnalysisDpt-CMC-MSU/ellipsoids#42]
Deadline: end of this semester
------------------------------------------------------------------------------------------------------
The goal of this task is to implement a few methods of "ellipsoid" class for "GenEllipsoid" class. 

A generalized ellipsoid is a set that can be represented as sum E+L, where L - a subspace of R^n and E is some (may be degenerate) ellipsoid in 
an orthogonal complement to L. A generalized ellipsoid doesn't have a configuration matrix in a common sense (by construction) but it does have
a) a basis in L and its complement.
b) a configuration matrix of E (ellipsoid in the orthogonal complement to L). 

You will have to refer to the generalized ellipsoid class implementation (elltool.core.GenEllipsoid class)
and its tests in 

		elltool.core.test.mlunit.GenEllipsoidTestCase
		elltool.core.test.mlunit.GenEllipsoidPlotTestCase

for a better understanding of how this class works.

Once you gain a sufficient level of confidence in your understanding of GenEllipsoid class please 
implement the following methods of ellipsoid class in GenEllipsoid class. 
Method names, format of input and output arguments should not be changed. 

isbigger
trace
shape
getShape
mtimes
parameters
plus
minus
polar
projection
fromRepMat
volume
maxeig
mineig
empty
trace
toStruct
hpintersect

All these methods should be covered with all kinds of tests that you need to put into 
elltool.core.test.mlunit.GenEllipsoidSecTC class. The test coverage should 
be very dense (different dimensions, all kinds of generalized ellipsoids, different combinations of
input parameters, both negative and positive tests).

**Comment by alextim27** [comment]
Do I understand right, methods inv and checkBigger existing in GenEllipsoid path - right, and I don't ave to implement these methods?

**Comment by pgagarinov** [comment]
checkBigger does exist but not isbigger. You need to provide a wrapper implementation of isbigger so that it calls checkBigger internally. The whole idea is to make GenEllipsoid provide exactly the same methods as "ellipsoid" class (with the same names and format of input/output arguments).

**Comment by alextim27** [comment]
I can't find the ellipsoid.empty implementation, where is it?

**Comment by pgagarinov** [comment]
empty is a built-in static method, it is implemented for all classes including double, int32 etc. Its implementation is hidden.

**Comment by alextim27** [comment]
1) Jenkins didn't start even try to test my branch
2) Are the implemented method ok? (Test coverage I will do a bit later)
3) Method shape. In ellipsoid class it returns shape matrix. But GenEllipsoid doesn't have this type matrix. In this case what this method has to do?

**Comment by pgagarinov** [comment]
1) I rebooted Jenkins - looks like there was some kind of software problem. Now everything looks fine.
2) Well, it doesn't look out of ordinary but I need to have a dense test coverage for all these methods until I can say anything. Until then - this is just some code. I suggest that you implement tests for the methods you already wrote first instead of writing new methods without any test coverage. 

3) it is getShapeMat method of ellipsoid class that returns a shape matrix. Both getShape and shape methods do something different - please read their help headers. Anyways, for a generalized ellipsoid getShapeMat method should return 3 outputs - the first is  eigvMat*diagMat*eigvMat.', the second is diagMat and the third is eigvMat. Same goes for "parameters" method - two additional outputs.

4) The best place is to study code in GenEllipsoid constructor (starting on line 138). 
Here is a brief explanation. If we assume for a second that GenEllipsoid represents a normal ellipsoid than a shape matrix of ellipsoid would be        eigvMat*diagMat*eigvMat.'  
However for a generalized ellipsoid there is no such thing as shape matrix so this representation is no longer valid. However we can still represent a generalized ellipsoid if we keep eigenVectors and their lengths separately. Thus in a generic case diagMat is a diagonal matrix that can contain both 0 and Inf on its diagonal. If diagMat(indDim,indDim)=Inf means that eigVMat(:,indDim) belongs to L (see a definition of generalized ellipsoid at the task description). Thus L is formed by those columns of eigVMat that correspond to Inf values on diagMat's diagonal. The rest of eigVMat's columns for an ellipsoid in an orthogonal complement of L.

5) Let us keep toStruct as it is because having qMat and qInfMat is much more human readable than having diagMat and eigVMat. Human-readability is important because toStruct is used by display function and for ellipsoid comparison as well.

**Comment by pgagarinov** [comment]
I had a look at the tests you added - this is definitely good as the first step but 

please

6) Do not call methods as functions - use ellObj.methodName() instead of methodName(ellObj). 
7) Do not call constructors without () - use GenEllipsoid() instead of GenEllipsoid.
8) There should be no MLint warnings (there should be a green box in the right upper corner) in all the code you work on. Right now this is not the case. Please fix that.
9) It is not necessary to return self from a test method. Writing a test with an output argument is possible only for a backward compatibility.
10) You should use mlunitext.assert(isOk); instead of mlunitext.assert_equals(true, isOk);
11) Think of a ways to make the code more structured via use of nested/sub-functions. This is not always possible but if there is a possibility - please use it.

Apart from that the test looks good.

**Comment by alextim27** [comment]
Ok. Can you see tests for plus and minus? Is this a good way to use constructions like

     testEllObj.(operation)(testVec)?

**Comment by pgagarinov** [comment]
12)
>Ok. Can you see tests for plus and minus? Is this a good way to use constructions like

> testEllObj.(operation)(testVec)?
Yes, it is ok.

13) Test for plus/minus are almost the same, I would suggest you write a combined testPlusMinus test that uses a nested function that contains all common code.

14) mlunitext.assert(leftArr==rightArr) is bad because assert expects a scalar logical variable while == returns an array

**Comment by alextim27** [comment]
13) Is it good idea to write PlusMinusTest function, which takes arguments: operation and testResVec, and to call it from testPlus as 
    self.PlusMinusTest('plus', testResVec)
where testResVec is constructed in each testPlus and testMinus?

**Comment by pgagarinov** [comment]
Yes but function name should be plusMinusTest. You can also make this a subfunction if place it outside of classdef/end. Then you can call it as plusMinusTest('plus',testResVec) i.e. without self.

**Comment by alextim27** [comment]
And I ask one more time to make it clean about getShape and shape. 
In ellipsoid methods written, that getShape returns copy of ellipsoid with modified Shape matrix. Method shape just modifies shape matrix of ellispoid. 
In GenEllipsoid case we would like to get the same. 
But what input arguments will be for shape() and GetShape()? 
eigvMat * diagMat * eigvMat.'? 
Or new diagMat and eigvMat?

**Comment by pgagarinov** [comment]
16) the logic should be backward-compatible with an ordinary ellipsoid. I suggest we modify eigvMat so that for diagMat without any Infs the resulting matrix would be

modMat*eigvMat * diagMat * eigvMat.'*modMat.'

Looking at this formula we see that replacing eigvMat with modMat*eigvMat would work even when diagMat contains some Infs. I.e. we keep diagMat intact and multiply eigvMat by modMat. And of course we check that this logic is backward-compatible with a plain ellipsoid (in the tests).

16) For trace there is no difference- you just use trace(self.getShapeMat()) where a shape matrix returned by getShapeMat() for GenEllipsoid can contains Infs. If so - trace will be equal to Inf which is ok, just cover such cases with tests.

**Comment by alextim27** [comment]
17) If I would like to use checkIsMe function --- I should realize it, right? 
18) If there are some troubles with existing checkBigger function - can I do some changes inside? (There are no input arguments checking at all)

**Comment by alextim27** [comment]
For this moment I finished with the following function (function + test)
fromRepMat
plus
minus
maxeig
mineig
parameters
isEmpty
toStruct

Can you check them?

**Comment by pgagarinov** [comment]
I will do that within next two days (today or tomorrow) but please do not wait for my feedback and proceed with implementing the rest of the functions for now.

**Comment by pgagarinov** [comment]
19) the most important problem with your implementation is that most method are just copy-pasted (and sometimes - slightly changed) versions of ellipsoid methods. This needs to be fixed so that

a) Methods that are 100% the same are moved to a base class so that both ellipsoid and GenEllipsoid inheriting this class have the same implementation
b) Methods that are almost the same are refactored such that the common part is moved to the base class in a form of protected method (possibly - with some additional parameters) and methods of ellipsoid and GenEllipsoid would then call these protected methods from their wrapper public methods. The goal is to 

a) Remove all copy-pasting
b) Keep it that the base class doesn't know anything about neither ellipsoid nor about GenEllipsoid classes. This means that you cannot reference these classes from the base class.

The problem is that if you use AGenEllipsoid as such base class then hyperplane will also inherit those ellipsoid specific methods so I'm afraid you will have to 

a) Rename AGenEllipsoid to ABasicEllipsoid
b) Create a new abstract class called AEllipsoid inherited from ABasicEllipsoid and use it as the base class for both ellipsoid and GenEllipsoid. This way hyperplane class will stay intact as it will be inherited from ABaseEllipsoid while all new protected methods will be added to AEllipsoid.

20) In plusMinusTest(self,operation,testResVec)
operation is a bad name - you should avoid using such simple names that can potentially cause conflicts
with some other functions in Matlab or 3rd party toolboxes, please use opName or methodName.
21) Bad names in

            testResVec=testEllVec.isEmpty();
            expResVec=[false,false,true,true,false];
            mlunitext.assert(expResVec==testResVec);

he have a special prefix for logical variables. Please fix other places - there is a lot of problems with
the variable names.

22) How can that be that isTestMat is a matrix while test5ResVec is a vector?

            isTestMat=exp5ResVec==test5ResVec;
            mlunitext.assert(all(isTestMat(:)));

Something is wrong here

23) please use nested functions to eliminate a copy-pasting in testToStruct and testFromRepMat
If you need to create variables like obj1, obj2,..., obj7 it just means that these variables
can be replaced with either an loop or just subfunction calls.

24) Please never use "eq" to compare ellipsoids in the tests, use isEqual with two outputs and use the 
second output in mlunitext.assert and assert_equals so that if test fails we can see why:

[isOk,reportStr]=obj1.isEqual(obj2);
mlunitext.assert(isOk,reportStr);

25) binOperWithVecNegativeTest can be made even more compact via nested functions, it is just too much of similar code.

26) In testParameters I suggest you put all the variables you compare in

            isTestMat=[isequal(test1DiagMat,exp1DiagMat),...
                isequal(test1CenVec,expCenVec),...
                isequal(test1EigvMat,exp1EigvMat);
                isequal(test2DiagMat,exp2DiagMat),...
                isequal(test2CenVec,expCenVec),...
                isequal(test2EigvMat,exp2EigvMat)];

into two structures and then just use modgen.struct.structcompare
instead of comparing all the variables in a pair-wise manner.

27) in findBasRank please rename "tolerance" variable into tolVal and please check other places for one word variable names. 
If there are any - please fix them as well.

**Comment by alextim27** [comment]
19) Sure it almost the same as in ellipsoid, just because it's written in task description. My task was to implement the same methods. 

To make it clear - the new structure will be the following:

![structure](https://cloud.githubusercontent.com/assets/14201400/11724684/710be8ba-9f86-11e5-9d9c-e492fdbb81f2.png)

And I have to move/refactor all methods in ellispoid and GenEllipsoid to make them inharited from AEllipsoid? 
What will be with tests? They will stay as they are? Specific tests for each class of ellipsoids? 

20-26) Ok, I will check all names

27) findBasRank - is not my function, but ok, I will check.

**Comment by pgagarinov** [comment]
19) Yes, this is correct.

>What will be with tests? They will stay as they are? Specific tests for each class of ellipsoids?
Yes, they will stay specific because I do not want you doing Nikita's work.

**Comment by pgagarinov** [comment]
>And I have to move/refactor all methods in ellispoid and GenEllipsoid to make them inharited from >AEllipsoid? 

Only those methods that have a common code, otherwise there should be an abstract method in AEllipsoid (without a body) while the actual implementation will be in the derivative classes.

**Comment by alextim27** [comment]
The question about headers in abstact classes. For example (check me please if it's wrong) - in ABasicEllipsoid class will be method isEmpty. 
In header, when I describe input arguments:
    % Input:
    %   regular:
    %       myEllArr: <classname> [nDims1,nDims2,...,nDimsN] - array of <classname>
    %            

instead of <classname> I have to write ABasicEllipsoid? 

And the same if method placed in AEllipsoid - can I use in the same place just ellipsoid or have to write AEllipsoid?

**Comment by pgagarinov** [comment]
The answer to all your questions is "yes".

**Comment by pgagarinov** [comment]
You have to write ABasicElliosoid and AEllipsoid

**Comment by alextim27** [comment]
So.. 
I did first steps of restructuring. ABasicEllispoid ans AEllipsoid added. 
Can you check, please, implemented methods, if I understood right what should I do.

**Comment by pgagarinov** [comment]
Sure, I'll make a detailed review tomorrow. Meanwhile, can you please squash all your commits up to 10th of December into a single commit? Otherwise each rebase generates too many comment messages in the task.

**Comment by alextim27** [comment]
Ok, I'll squash commits. 
By the way - can I move all implementation of methods to separate files? I.e. in each class will be only signatures, and all code will be in files? For me this view is better and easier to understand what class can do and consist of.

**Comment by pgagarinov** [comment]
Yes, you can.

**Comment by pgagarinov** [comment]
Well, it is hard to tell when some of the tests do not pass. The most obvious mistake I noticed is absence of getRelTol and relTol in ABasicEllipsoid. Please make all the tests first and squash the commit. After that I'll make a detailed review.

**Comment by alextim27** [comment]
All tests passed. I did some new tests for methods.

**Comment by pgagarinov** [comment]
Ok, great. I'll have a look the first thing tomorrow.

**Comment by pgagarinov** [comment]
Very good job indeed! I'll continue my review tomorrow, especially of the tests, meanwhile can you please

28) Move ellipsoid.dimension ->BaseEllipsoid (please slight modify the method by replacing getShapeMat with centerVec - this way this method will work for all 3 classes). Then remove dimension from ellipsoid, hyperplane and GenEllipsoid classes.

29) remove eq from GenEllipsoid - it is inherited from ABasicEllipsoid

30) merge to master (after rebase of course - Ilya has merged his changed to the master once again) what you already have - I want other students have these structural changes in the master (especially Elena Ivanova since her work will be based on your changes).

**Comment by alextim27** [comment]
28) I think it's wrong what you wrote, because 
a) For ellipsoid size of centerVec != dimension
b) centerVec is not initialized in hyperplane constructor -> it's not used. 

I did absrtact method dimension. In hyperplane saved old code, from ellipsoid and GenEllipsoid moved to AEllipsoid with calling getShapeMat() method. 

29) Done
30) Wait for tests result

**Comment by pgagarinov** [comment]
Yes, please revert commit "9d88ba8e8900c2cfcc1dfeb7fb7e0315e571ec48" and make sure that no commit ever changes files not related to your task. 

28) Then I think we need to move centerVec from ABasicEllipsoid to AEllipsoid and move ellipsoid.dimensiton to AEllipsoid replacing getShapeMat with getCenterVec.

**Comment by pgagarinov** [comment]
31)something is wrong with getCenter - it is called from many places:

GenEllipsoidPlotTestCase.m	278	qCenVec = testEll.getCenter();
GenEllipsoidPlotTestCase.m	291	qCenVec = testEll.getCenter();
GenEllipsoidPlotTestCase.m	301	qCenVec = testEll.getCenter();
GenEllipsoidPlotTestCase.m	314	qCenVec = testEll.getCenter();
GenEllipsoidPlotTestCase.m	337	qCenVec = testEll.getCenter();
GenEllipsoidTestCase.m	799	ellApx=GenEllipsoid(ellApx.getCenter(),ellApx.getDiagMat(),...
GenEllipsoidTestCase.m	1091	resEllObj=GenEllipsoid(ellObj.getCenter(),ellObj.getDiagMat(),newVMat);
GenEllipsoidTestCase.m	1111	cenVec=resEllipsoid.getCenter();
parameters.m	43	ellCenterVec=ell.getCenter();
parameters.m	46	ellCenterVec=ell.getCenter();
plot.m	105	xMat = plotEll.getCenter();
plot.m	136	qVec = plotEll.getCenter();
plot.m	161	qCenVec = ell.getCenter();
plot.m	187	ellCenVec = ell.getCenter();
plot.m	218	qCenVec = ell.getCenter();
rho.m	27	cenVec=ellObj.getCenter();


but I do not see where it is defined. The big question is - why do the tests still pass? It looks like the tests that should fail do not fail.
In this particular case I'm more concerned with the tests not covering this problem, not with the problem itself. Please investigate. 



32)you need to start properties nPlot2dPoints and nPlot3dPoints in all 3 classes, not just in ellipsoid (see my comments above where I described how to do it).
33) testIsBigger - we need positive tests as well, not just negative
34)in the tests please always use the second output of "isEqual":

mlunitext.assert(isEqual(resEllArr,expEllArr)); is bad, use

[isOk,reportStr]=isEqual(resEllArr,expEllArr);
mlunitext.assert(isOk,reportStr); instead
35) products/+elltool/+core/@ABasicEllipsoid/getScalarPolarInternal.m should not be in BasicEllipsoid because this method is ellipsoid-specific. AEllipsoid should 
have this method defined as Abstract, GenEllipsoid and ellipsoid should have different implementations of this method.
36) in mineig and maxeig do you really need to have the following "if" operator calls?

function minEig=getSingleMinEig(ellObj)
    shapeMat=ellObj.getShapeMat();
    if min(shapeMat(:))==Inf
        minEig=Inf;
    elseif isnan(min(shapeMat(:)))
        minEig=NaN;
    else
        minEig=min(eig(shapeMat));
    end
end

After all

>> min(nan)

ans =

   NaN

>> min(inf)

ans =

   Inf

>> max(Inf)

ans =

   Inf

**Comment by alextim27** [comment]
31) Yes, you're right. I changed getCenter in last commit and tests will not pass. I moved it to AEllipsoid and forgot to rename everywhere it's called.
36) Yes, I need, because I didn't find how to call eig function with Inf/nan comprising matrix.

**Comment by alextim27** [comment]
28) Moved, but I still don't understand, why we need to replace getShapeMat to getCenterVec? It will give not right results. 
31) Done.
32) In progress. 
33) Done.
34) Done. 
35) Moved. Implementation in GenEllipsoid will do.

**Comment by pgagarinov** [comment]
28) because it will be faster - getCenterVec just returns a value of centerVec field for all types of ellipsoids while GenEllipsoid.getShapeMat reconstructs a matrix thus doing an unnecessary job.

**Comment by alextim27** [comment]
28) Changed to getCenterVec in size-case, in rank case I left getShapeMat, because changing it to centerVec will give the wrong answer
32) Can you explain, how change hyperplane's plot?

Can I merge to master current version or keep working?

**Comment by pgagarinov** [comment]
I fixed a few cosmetic problems in your branch - please do Pull with rebase flag (Important!)

32) After having a closer look at hyperplane.plot it appears like we do not need nPlot2dPoints and nPlot3dPoints in hyperplane after all. So please move this properties to AEllipsoidClass.
36) Along with these properties please move getNPlot2dPoints and getNPlot3dPoints methods from ellipsoid class. 

37) Also please do not forget about getAbsTol, getRelTol - they need to be deleted from all the classes but the class where they are defined (i.e. in ABasicEllipsoid). Just check if there are some other methods that should be deleted from ellipsoid class.
38) centerVec should moved from ABasicEllipsoid to AEllipsoid, right?

Once you do all this please merge and then continue in a re-created branch.

**Comment by alextim27** [comment]
Finally I leave properties in ABasic, but methods moved to AEllipsoid.

**Comment by pgagarinov** [comment]
Why?

**Comment by alextim27** [comment]
Because if I move them to AEllipsoid I'll not have access to nPlotXdPoints from getProperty method (because getProperty implemented in ABasicEllipsoid, nPlotXdPoints - properties of inherited class). To have an access I need to implement getProperty in AEllipsoid too, but it will have the copy-pasted code.  
The same with centerVec. 
I asked how to solve this problem and you told me move these properties to ABasicEllipsoid. 

So, if there is any other solution that I don't see, tell me please

**Comment by pgagarinov** [comment]
I suggest we do the following:

a) Create an abstract public getProperty method in ABasicEllipsoid and a non-abstract static protected getPropertyInternal method, the body of current getProperty will go into getPropertyInternal
b) In ellipsoid,GenEllipsoid and hyperplane classes create define public getProperty method that will call getPropertyInternal from ABasicEllipsoid.

This will solve the problem with the access permissions and mostly solve the problem with copy-pasting.

But it is still not clear why you need centerVec in ABasicEllipsoid, after all it doesn't make sense to use getProperty method for accessing centerVec, right?

**Comment by pgagarinov** [comment]
Please have a look at my last commit to master - you should always use import statements prior to a class usage, otherwise old versions (like Matlab2013b) won't be able to run such code. Thanks.

**Comment by alextim27** [comment]
Yes, ok.

**Comment by alextim27** [comment]
If we consider the GenEllipsoid represented as E+L, where L - a subspace of R^n and E is some ellipsoid in an orthogonal complement to L.
Do I think right, that the polar of this GenEllipsoid is sum p + L, where p is the polar of ellipsoid E?

**Comment by pgagarinov** [comment]
Of course no. If you figure out what polar of R^N is you will see that it is not R^n.

**Comment by pgagarinov** [comment]
I found a few serious problems in your previous commit to the master. Can you please fix them asap, merge to master and only then proceed with polar implementation?

39) ellipsoid.fromRepMat - your changes to this method just do not make any sense. First of all the help header is all about the generalized ellipsoid while the method is in ellipsoid class. Secondly, why do you have fromRepMatInternal method in ABasicEllipsoid class but help header for fromRepMatInternal just doesn't make any sense. Also name fromRepMatInternal doesn't make any sense either. Please rename fromRepMatInternal into repMat, make it public and make sure it does have a correctly-written help header. Finally, ellFactory method is not needed - please remove it and use feval(class(ellObj)) in repMat method.

40) help header for ellipsoid.trace for some reason refers to class AEllipsoid, not ellipsoid, Please fix that. I suspect that this is not the only place where this problem occurs, please check all other methods that you changed and make sure that the classes mentioned in their help headers are correct.

41) ABasicEllipsoid.getPropery's internal name is getPropertyInternal which causes mlint problem. Please make sure that all functions you changed have no mlint warnings. Use mlintrpt command for that:

mlintrpt('C:\Users\Administrator\Documents\_Git\ellipsoids\products\+elltool\+core\@ABasicEllipsoid','dir')

42) please remove getPropList method, instead I think we need to modify getProperty method by removing these lines:


propNameList=ellArr.getPropList();
if ~any(strcmp(propName,propNameList))
    throwerror('wrongInput',[propName,':no such property']);
end

Then, if some property doesn't exist the following line will fail with a nice-looking message:


    propArr(iElem)=ellArr(iElem).(propName);

so getPropList is not really needed.

**Comment by alextim27** [comment]
40) 41) I've already fixed in last commit with some other problems.

39) 42) Will fix it tomorrow

43) To make it clear - I made changeShapeMatInternal in both of ellipsoids class. And after this implementation I moved mtimes and shape to abstract class, and these methods use changeShapeMatInternal. Is it ok?

**Comment by pgagarinov** [comment]
43) Yes, looks good, just replace ' with .' in shMat=modMat*(ellObj.getShapeMat())*modMat';

**Comment by pgagarinov** [comment]
44) There is one more problem - the way formCompStruct is implemented in ellipsoid class. For some reason ellipsoid's version takes into account nPlot2dPoints while GenEllipsoid's version doesn't. To avoid  the copy-pasting I suggest we fix this by a) making this method a protected non-static (let it ignore the first input, non static methods can be overridden more robustly. b) providing an correct implementation of this method in all the classes including AEllipsoid and ABasicEllipsoid. When you define this method in AEllipsoid you should call a method of parent's class first:

function SComp=formCompStruct(self,SEll)
     SComp=formCompStruct@elltool.core.ABasicEllipsoid(self,SEll);
     %add absTol and relTol fields
end

This way there won't be any copy-pasting because in each implementation you will be just handling properties added in the current class.

**Comment by alextim27** [comment]
39) 42) 43) Done.
44) I did it the way you said but it made some tests Failed. As I understand It's Elena's task to make it works right way. What should I do?

**Comment by pgagarinov** [comment]
I do not see the test results just yet so it is hard to tell just yet. Let us see for the test results on the server and then decide.

**Comment by alextim27** [comment]
Ok. 

Returning to polar. 
As I understand the polar set of G (G is generalized ellipsoid):
P = {y in R^n | <y, e + l > <= 1  for all e in E and l in L}. 

So polar set of L is orthogonal complement to L? 
If yes, why the polar of E in orthogonal complement to L is not polar of G?

**Comment by pgagarinov** [comment]
44) You shouldn't have copied my code blindly as it contained a few misprints, here is a correct version. 

nFields=numel(fieldNameList);
%
for iField=1:nFields
fieldName=fieldNameList{iField};
if isempty(SEll.(fieldName))
SComp.(SFieldNiceNames.(fieldName))=[];
else
SComp.(SFieldNiceNames.(fieldName))=SEll.(fieldName);
end
end

Please verify what I write and say, do not just copy my code blindly.

Anyways, tests fail not because of this problem - the reason they fail is because Q in

SFieldNiceNames = struct('shapeMat', 'Q', 'centerVec', 'q');

is actually a square root of shapeMat. This is because when we compare matrices via structcompare we want to compare something that depends on precision linearly, not quadratically.

The way to fix this is 

a) Introduce an additional output to toStruct function that returns a structure with a transformation function for each field, for ellipsoid it will be 

SFieldTransformFunc = struct('shapeMat', @(x)gras.la.sqrtmpos(x, absTol), 'centerVec', @(x)x);

b) make isEqualInternal pass this structure into formCompStruct
c) make formCompStruct use

fTransfomr=SFieldTransformFunc.(fieldName);
SComp.(SFieldNiceNames.(fieldName))=fTransfomr(SEll.(fieldName));

instead of just

SComp.(SFieldNiceNames.(fieldName))=SEll.(fieldName);

Also please rename Q in

SFieldNiceNames = struct('shapeMat', 'Q', 'centerVec', 'q');

to "QSqrt" because Q is a square root of shapeMat.

For GenEllipsoid QInf and Q should also be renamed and please use correct transformation functions in GenEllipsoid as well. 

Thus test tests do not pass because right now you compare shapeMat's, not sqrtm(shapeMat);

**Comment by pgagarinov** [comment]
45) Answer to this question depends on what you mean by "the polar of E in orthogonal complement to L". If you mean that polar of E+L is projection of polar(E) to an orthogonal complement to L then I think you are right. But if you mean that polar of E belongs to an orthogonal complement to L then you are wrong (the simplest case if when E is degenerate). 

46) Yes, I think this is correct.

**Comment by alextim27** [comment]
44) SFieldTransformFunc = struct('shapeMat', @(x)gras.la.sqrtmpos(x, absTol), 'centerVec', @(x)x);
Which absTol it uses, if input of toStruct is array of ellipsoid?

**Comment by pgagarinov** [comment]
absTol from isEqualInternal

**Comment by alextim27** [comment]
Ok.

47) Can you please have a look at tests EllipsoidBasicSecondTC/testGetProjection and EllipsoidBasicSecondTC/testProjection? 

In EllipsoidBasicSecondTC/testGetProjection lines
591/592:
    dimVec = [0,0,2,0];
    auxTestProjection('getProjection',centVec, shapeMat, projMat, dimVec);
728:
ellArr = ellObj.repMat(dimVec);

Now it's failing, because dimVec contains zeros. 
But in previous versions of repMat were jast 3 lines 

function resArr=repMat(self,varargin)
sizeVec=horzcat(varargin{:});
resArr=repmat(self,sizeVec);
resArr=resArr.getCopy();

And test passed. 
Can you explain please, why it worked before and what I have to do with it now?

**Comment by pgagarinov** [comment]
Where did the new implementation of repMat come from?

**Comment by alextim27** [comment]
in 39) You said rename fromRepMatInternal to repMat. I looked at these two functions and decided they are similar. So I deleted old repMat and replaced it with fromRepMatInternal renamed to repMat.

**Comment by pgagarinov** [comment]
I'm not in front of a computer right now - will take a look later today or tomorrow. But presumably all we need to do is to allow zeros in sizeVec, in which case the result should be the same as built-in "empty" method returns.

**Comment by alextim27** [comment]
44) Done. 
46) Volume is done.
47) I fixed repMat and question is solved
48) EllipsoidTestCase/testMtimes, test in line 1230 is wrong. Because author author calculated result using ' istead of .' with complex matrix. 
If replace ' with .' - there will be error in ellipsoid constructor:
Error: Norm of imaginary part of sourse object = 0.70252. It can not be more than tolVal = 2.2204e-16, Identifier: GRAS:LA:TRYTREATASREAL:wrongInput:inpMat

**Comment by alextim27** [comment]
45) I mean that if G = E + L, than P = polar(G) is 
P = {y in L^T | <x, y> <= 1 for all x in E}, where L^T is orthogonal complement to L. 
Is this right?

**Comment by pgagarinov** [comment]
45) I think so but please write extensive tests, especially for ellipsoids with non-zero centers and make sure that polar for GenEllipsoid = polar of ellipsoid when L is empty and E is not degenerate
b) that polar (polar(G))=G for a variety of cases

Btw - looking at your changes right now....

**Comment by pgagarinov** [comment]
49) in formCompStruct there is a misprint in "fTransfomr"

50) repMat error message 'size vector must contain positive integer values.' doesn't 
seem correct as we allow non-negative elements in sizeVec, not just positive - right?

51) Please put functionality of ellipsoid.volume into AEllipsoid.ellVolume and rename ellVolume into volume.
One of the important properties of protected methods is that they can be overriden so your 
implementation of GenEllipsoid.volume will call AEllipsoid.volume if ~any(qInfMat(:)>0) and 
return Inf otherwise. ellipsoid class in its turn will just inherit an implementation of volume
method from AEllipsoid. Also I do not think you need to create another object in case ~any(qInfMat(:))>0 like now:

    if ellObj.isEmpty()
        simpleEllObj=ellipsoid();
    else
        simpleEllObj=ellipsoid(ellObj.centerVec,ellObj.getShapeMat());
    end

just call volume@elltool.core.AEllipsoid(self) and that is it.

52) Please make sure there is a negative test for each method of GenEllipsoid you implemented (consider all representative cases of incorrect input arguments).

53) fSingleProjection as a name is good for a variable containing a function handle but not for a function or a method. Please rename fSingleProjection into
projectionSingleInternal
54) Implementation of GenEllipsoid.isdegenerate doesn't seem to be correct. Generalized ellipsoid E+L is degenerate if and only if L is empty and E is degenerate. 
There is no need to use     gras.la.ismatnotdeg(ellObj.getQInfMat(),ellObj.getAbsTol()); especially with absTol to make sure that L is empty. Please make sure that
you have a proper test coverage for that.


55) Please rename changeShapeMatInternal into "shapeSingleInternal and make sure you use ".'" instead of "'" in
   shMat=0.5*(shMat + shMat');

56) In all the help headers, in hyperplane.fromRepMat for instance 

%			sizeVec: double[1,n] - vector of size, have
%			integer values.

should look like 

%			sizeVec: double[1,n] - vector of size, have
%				integer values.

i.e. lines that follow the line with a parameter name should have an additional leading tabulation. Also please avoid using "n" to denote sizes of input arguments, 
names of dimensions should be self-representative like "nDims" for instance.

Compare 

%	Case3:
%		regular:
%			normalVec: double[nDim, 1] - normal of
%			hyperplanes.
%			shift: double[1, 1] - shift of hyperplane.
%			sizeVec: double[1,n] - vector of size, have
%			integer values.

and 


%	Case3:
%		regular:
%			normalVec: double[nDim, 1] - normal of
%				hyperplanes.
%			shift: double[1, 1] - shift of hyperplane.
%			sizeVec: double[1,n] - vector of size, have
%				integer values.

the latter example is much more readable.



57) Why do you have to have different implementations of "volume" for ellipsoid and GenEllipsoid classes when implementation of "trace" is common for both of them? Also look like
there is no any test for "trace" for GenEllipsoid.

58) regarding 48) - I think that the previous implementation of mtimes where conjugation "'" was used instead of transposition ".'" was correct because 
(x,Ay)=(A*x,y) where * is conjugation, not transposition. For real-valued operators transposition = conjugation.  So please switch back to "'" in changeShapeMatInternal and revert your changes to the test.


Can you please fix all the problems above, merge to master and only then proceed with implementation of the rest of the methods? Thanks.

**Comment by alextim27** [comment]
49-51, 53-55, 58) Done.
52,56,57) - for tomorrow.

**Comment by alextim27** [comment]
57) The question is in the following:
Shape matrix of GenEllipsoid now can contain NaN, because if in diagMat there are Inf and in eigvMat there are zeros, than there are NaNs in shapeMat. 
And now there are to ways to calculate shape matrix - first implemented in toStruct, second in getShapeMat. Can you please suggest what way we have to use?

**Comment by pgagarinov** [comment]
qMat calculated in toStruct is actually a configuration matrix of E in G=E+L representation while qInfMat something like a configuration matrix of L. Both volume and trace for non-empty L should return If so I do not see why we should not use getShapeMat's impementation, we just need to override the implementation of tracer and volume from AEllipsoid class like this:

volumeVal = volume@elltool.core.AEllipsoid(self);
if isnan(volumeVal)
      volumeVal=Inf;
end

because in theory the only case when we get Nan is when L is not empty. But please make sure in the tests that you cannot get Nan for a degenerate ellipsoid for instance, we do not want volume return Inf volume for an empty-interior set. Same goes for trace method.

**Comment by pgagarinov** [comment]
Please note that it is better to merge to master a partial implementation than have an incomplete implementation not merged.

**Comment by alextim27** [comment]
Yes, sure. 
I almost did all items you wrote. There are some headers to fix left. Today will push

**Comment by alextim27** [comment]
I hope I did every item 49-58) 

Can you please have a look again to Jenkins, my branch didn't start to test

**Comment by pgagarinov** [comment]
Done except for polar and hpintersect methods. These methods will be implemented as part of issue #46
