### ISSUE TITLE
Create demo for a pendulum with a flywheel

### ISSUE THREAD

**Issue by irublev** [SystemAnalysisDpt-CMC-MSU/ellipsoids#55]
This issue is a part of issue #53.

**Comment by irublev** [comment]
What remains to do --- the items 4 and 5 from the text of issue #53.

**Comment by ShalnovYar** [comment]
Good afternoon, if I understood correctly, to remake commits I should make a hard reset to the last commit before mine and make a push, then I should again make all my commits and push them again?

**Comment by irublev** [comment]
Yaroslav, it means that yes, you should do all anew. But it is not sufficient just to make a hard reset. In fact, you need, for example, to make stash save (before this hard reset, just to save the results of your work), only after this you need to reset your local repository to the last commit immediately before your ones, after this you should perform a rebase, then you can pop your stash, commit results and push them into our remote repository.
