### ISSUE TITLE
Fix testBackward in ContinuousReachFirstTestCase and make it pass

### ISSUE THREAD

**Issue by pgagarinov** [SystemAnalysisDpt-CMC-MSU/ellipsoids#9]
Test testBackward in \products\+elltool\+reach\+test\+mlunit\ContinuousReachFirstTestCase.m is not finished. The idea of the test is to use the ellipsoidal tube cut at t_1 and use the resulted ellipsoid as an initial set for calculating the reachability domain. Then compare the resulted domain with the domain in direct time.

**Comment by arturlu** [comment]
@pgagarinov The current test implementation loads system definition and initial conditions from demo3firstBackTest.xml config file for the backward pass. It is confusing me. In fact, the backward system must be constructed from the forward one by reversing timeVec and changing initial set.

Am I correct with understanding that we need:
1. compute reach set for already defined forward system
2. compute its external and internal approximation at `t_1`: `rf(t_1).ea` and `rf(t_1).ia`
3. construct two backward reach set (one with `rf(t_1).ea` as initial set, other with `rf(t_1).ia`): `rbe` and `rbi`
4. check that `rbi(t_0).ia` inside `rf(t_0)` and `rbe(t_0).ea` is bigger `rf(t_0)` ?

**Comment by pgagarinov** [comment]
>Am I correct with understanding that we need:
>1. compute reach set for already defined forward system
This is correct but the forward set is already calculated in `set_up_param` method that is called prior to each test. So all you need to do is to use self.reachObj.
>2. compute its external and internal approximation at t_1: rf(t_1).ea and rf(t_1).ia
Already calculated inside of self.reachObj.
>3. construct two backward reach set (one with rf(t_1).ea as initial set, other with rf(t_1).ia): rbe and rbi
>4. check that rbi(t_0).ia inside rf(t_0) and rbe(t_0).ea is bigger rf(t_0) ?
There is a difference between solvability and reachability domains. rf(t_1) is a reachability domain i.e. a set of points such that x(t_1) is inside rf(t_1) for ANY u(t). rbe(t_0) and rbi(t_0) are solvability domains. Solvability domain rbe(rbi) consists of all points from which rf(t_1).ea (rf(t_1).ia) is reachable for SOME control u(t). Thus the only thing we can check in terms of inclusions is that rf(t_0) is inside rbe(t_0). However we can also check rbi(t_0) has a non-empty intersection with rf(t_0)=X_0 and that this intersection does always contains a maximizer of support function for X_0 along direction l_i(t_0) when rfi is built for rf(t_1).ia along l_i(t).

**Comment by arturlu** [comment]
@pgagarinov So, we must have 3 checks:
* x0 inside rbe(t0).ea
* rbi(t0).ea intersects x0
* the above intersection contains maximizer of support function (if rbi was initialized by direction rf(t1).get_direction())

I have implemented the first 2 checks.
However, the last one can't be implemented now, because of 
`[dirsCVec, timeVec] = ReachContinuous.get_directions()` returns the outputs with different size: numel(dirsCVec) != numel(timeVec) ([this line](https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/commit/7c3d6066cdca389005570fb421d5f89e1ef34437#diff-c74b2f286b3c9570e8644f87d167f399R150)) and I can't initialize backward solver by directions at t1

**Comment by pgagarinov** [comment]
It is normal that they have different size - please have a look at the help header I added in master for "get_directions" method. Actually, you can also use get_goodcurves method as well.

**Comment by arturlu** [comment]
@pgagarinov Ok. Additional checks were made. Can I make rebase & merge to close the issue?

**Comment by pgagarinov** [comment]
1) Please replace ABS_TOL and REL_TOL with the tolerances that are derivative from
the tolerances extracted from reachObj. The goal is to make your test work even when 
tolerances used by ReachContinuous change (they are extracted from both xml configuration used 
by the tests (regTol) and global xml configuration for the whole toolbox (elltool.editconf)).
Use getAbsTol and getRelTol methods of ReachContinuous and some kind of multipliers to get 
your absCompTOl and relCompTol (they are not constants anymore).

2) In all assert(assert_equals) calls please specify the second (and the third parameter)
with a diagnostic message so that if a test fails we can see an informative message.
3) If dirsT0Equal is logical where is "is" prefix?

4) Please use method-wise calls instead of function-wise calls where possible:
objVec.methodName(arg1,arg2,...) instead of methodName(objVec,arg1,arg2,...)

5) make the names a bit more informative so that the main part of the name comes first:
x1eaEll-> ellEaCutAtT1. Just keep in mind that the main part of the name is the one that
is indicative of the object type ("ell" in the case above). 
x0Ell->ellX0
dirVec-> l0CurVec

**Comment by arturlu** [comment]
@pgagarinov 
> x1eaEll-> ellEaCutAtT1. Just keep in mind that the main part of the name is the one that
is indicative of the object type ("ell" in the case above)
But according to [the codestyle document](https://github.com/SystemAnalysisDpt-CMC-MSU/ellipsoids/wiki/Coding-policy), main part of variable name (`Ell` in the example) is placed at the end of the name.

**Comment by arturlu** [comment]
BTW `self.reachObj.getRelTol()` call fail:
>The class elltool.reach.AReach has no Constant property or Static method named 'getProperty'.
>
>Error in elltool.reach.AReach/getRelTol (line 340)
>            [relTolArr, relTolVal] = elltool.reach.AReach.getProperty(...

Therefore I will use `TOL_MUL*self.reachObj.getAbsTol()` instead of self.reachObj.getRelTol()

**Comment by pgagarinov** [comment]
>But according to the codestyle document, main part of variable name (Ell in the example) is placed at >the end of the name:
This is just to stress that the names should start with a small letter. If you insist on your names - I'm fine with that, just add "is" prefixes where needed.

>Therefore I will use TOL_MUL*self.reachObj.getAbsTol() instead of self.reachObj.getRelTol()
I fixed this bug in master, please use getRelTol(). If you encounter other bugs - please fix them by yourself instead of working around them. This is already a second time when you said "I cannot proceed because something doesn't work". You are a developer, not an end user and you can read and change source code. This is a working practice course that requires you to solve real-life problems, not a bunch of purified academic tasks. On a real job you will most likely be asked to push through to get the job done, an argument that you can't do something because it doesn't work as said in a manual won't work. The goal of writing a test is to find and fix bugs. The test is useless if it always passes.

**Comment by arturlu** [comment]
@pgagarinov Done.

BTW I avoided fixes in another parts of the project, because of the pipeline assumes creating issue, branch, additional review and many other steps-))

**Comment by pgagarinov** [comment]
Which issues have you avoided? I need to know so that I can create issues and fix them later.

**Comment by arturlu** [comment]
@pgagarinov The two ones already mentioned above.

**Comment by pgagarinov** [comment]
6) idxVec->indVec, ABS_TOL->absTol, REL_TOL->relTol
7) please replace strcat('a','b') with ['a','b']

**Comment by arturlu** [comment]
@pgagarinov Ok.

**Comment by pgagarinov** [comment]
If all tests pass after rebase - you can merge to master. To get "zachet" you need to complete at least one more task (any) from the remaining two.

**Comment by arturlu** [comment]
@pgagarinov Something strange with server testing.
Testing on the server was failed on both R2015b* architectures before any test had run.
All 891 were passed on R2013b win64 architecture but the build has status Aborted.

**Comment by pgagarinov** [comment]
No worries, I had to reboot the server a few times during an overnight backup procedure to fix a few problems, as far as I can see all the tests pass in master. So I'm closing this task.
